api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":85"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: conference-balancer
    watch: true

log:
  level: "DEBUG"  # Set to DEBUG for detailed logs

accessLog: {}  # Enable access logs
