name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "${{ secrets.PROJECT_PATH }}/.git" ]; then
              mkdir -p $(dirname ${{ secrets.PROJECT_PATH }})
              git clone ${{ secrets.GIT_REPO }} ${{ secrets.PROJECT_PATH }}
            fi

            cd ${{ secrets.PROJECT_PATH }}
            git checkout master
            git fetch --all
            git reset --hard origin/master
            git pull origin master
            docker-compose down
            docker-compose up -d --build
